name:        network-zmq-unagi
version:     0.0.1.0
synopsis:    put/take messages to/from zeromq via unagi channels
description: See README at <https://github.com/haroldcarr/network-zmq-unagi
author:      Harold Carr
github:      haroldcarr/network-zmq-unagi
category:    network
license:     BSD-3-Clause

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- async
- base >=4.11 && < 5
- cereal
- cereal-text
- containers
- fast-logger
- protolude
- mtl
- text
- unagi-chan
- zeromq4-haskell

library:
  source-dirs: src

_exe-ghc-options:        &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  main:
    source-dirs:         app
    main:                ZMQExample.hs
    other-modules:       ""
    ghc-options:         *exe-ghc-options
    dependencies:
      - network-zmq-unagi

tests:
  test:
    source-dirs:         test
    main:                Main.hs
    other-modules:       ""
    ghc-options:         *exe-ghc-options
    dependencies:
      - network-zmq-unagi
      - hedgehog
